### ISSUE TITLE
you need the extended version to build SCSS/SASS

### ISSUE THREAD

**Issue by sljdxde** [miiiku/hugo-theme-kagome#1]
centos上安装的，是不是需要安装其他的组件。目前hugo已经是最新版本了

**Comment by miiiku** [comment]
并不需要单独安装其他组件，你可以看下这条issues能否帮到你 [https://github.com/gohugoio/hugo/issues/7182](https://github.com/gohugoio/hugo/issues/7182)

**Comment by sljdxde** [comment]
> 并不需要单独安装其他组件，你可以看下这条issues能否帮到你 [gohugoio/hugo#7182](https://github.com/gohugoio/hugo/issues/7182)

问题已解决！安装了扩展版本。
一个新的问题，我看你的example site里，文章都有背景图，这个是怎么设置的呀？

**Comment by miiiku** [comment]
在文章md文件头部`Front Matter`种添加`cover: [图片url]`即可，详见[https://kikyo.cc/posts/202106180929/](https://kikyo.cc/posts/202106180929/)

**Comment by SmithWillSuffice** [comment]
No guarantee this will work for you, but if you get a hugo build error try checking to see if your .gtihub/workflows/gh-pages.yml has something like,
```
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
```
If instead you see `# extended: true` then uncomment it!
